# lightning.pytorch==2.5.1.post0
# Inference configuration - minimal config that will be merged with training config from checkpoint
seed_everything: true

trainer:
  accelerator: gpu
  devices: 1
  num_nodes: 1
  precision: 16-mixed
  logger:
    class_path: lightning.pytorch.loggers.TensorBoardLogger
    init_args:
      name: infer_ew_xfmr
  callbacks:
    - class_path: ml.callbacks.prediction_writer.EWPredictionWriter
      init_args:
        file_prefix: ew_predictions  # Override with --trainer.callbacks.init_args.file_prefix="your_prefix"
        write_interval: epoch

# Inference-specific overrides - these will override training config
model:
  class_path: ml.modules.trace_ew_module.TraceEWModule
  init_args:
    use_laplace_on_fit_end: false  # Disable Laplace for inference
    compile_model: false  # Disable compilation for inference

# Inference data configuration - uses InferenceTraceSeqEWDataloader
data:
  class_path: ml.data.eyewidth_data.InferenceTraceSeqEWDataloader
  init_args:
    batch_size: 100