# lightning.pytorch
seed_everything: true

trainer:
  accelerator: gpu
  devices: -1
  precision: 32
  max_epochs: 50
  logger:
    class_path: lightning.pytorch.loggers.TensorBoardLogger
    init_args:
      save_dir: saved
      name: snp_ssl
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: train_loss
        dirpath: saved/snp_ssl/checkpoints
        filename: snp-encoder-{epoch:02d}-{train_loss:.5f}
        auto_insert_metric_name: false
        save_last: true
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: step
    - class_path: ml.callbacks.visualization_callbacks.SParameterVisualizer
      init_args:
        num_samples: 1

model:
  class_path: ml.modules.snp_ssl_module.SNPSelfSupervisedModule
  init_args:
    model_dim: 768
    freq_length: 256
    encoder_type: OptimizedSNPEmbedding
    decoder_hidden_ratio: 2
    reconstruction_loss:
      class_path: ml.utils.snp_losses.SNPReconstructionLoss
      init_args:
        magnitude_weight: 1.0
        phase_weight: 0.5
        latent_reg_weight: 0.001
    latent_regularization_type: l2
    latent_regularization_weight: 0.001

data:
  class_path: ml.data.snp_dataloader.SNPDataModule
  init_args:
    data_dirs:
      - /proj/siaiadm/AI_training_data/D2D/vertical/snp_for_UCIE_20250121
      - /proj/siaiadm/AI_training_data/D2D/from_enzo
    file_pattern: "*.S96P"
    batch_size: 2
    num_workers: 0
    pin_memory: false
    cache_in_memory: true

optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 5e-4
    weight_decay: 1e-5

lr_scheduler:
  class_path: ml.utils.lr_schedulers.CosineAnnealingWarmRestartsWithWarmupDecay
  init_args:
    T_0: 10
    T_mult: 2
    eta_min: 1e-6
    warmup_epochs: 5
    decay_factor: 0.95

# Optional: Override for testing with smaller dataset
# ckpt_path: null  # Path to resume from checkpoint 