# Data Collection Configuration for EyeDiagramNet Training Data
# This config defines parameters for collecting eye width simulation data
# Used by: simulation.collection.training_data_collector

collection:
  # Directory paths
  trace_pattern: "./test_data/traces"  # Directory containing trace SNP files
  vertical_dir: "./test_data/vertical"  # Directory containing vertical SNP files for TX/RX
  output_dir: "./data/training_samples"  # Output directory for collected data
  
  # Parameter sampling configuration  
  param_type: "MIX_PARAMS"  # Options: DDR_PARAMS, HBM2_PARAMS, UCIE_PARAMS, MIX_PARAMS
  max_samples: 50  # Maximum number of samples to collect per trace SNP
  
  # Processing configuration
  max_workers: 8  # Maximum number of worker processes (null for auto-detect CPU count)
  proc_per_gpu: 1  # Number of processes per GPU (currently not used with CPU simulation)
  
  # Debug and logging
  debug: false  # Enable debug mode for sequential processing and verbose output
  
# Alternative configurations for different use cases
profiles:
  # Quick test with minimal samples
  test:
    trace_pattern: "./test_data/traces"
    vertical_dir: "./test_data/vertical" 
    output_dir: "./data/test_samples"
    param_type: "MIX_PARAMS"
    max_samples: 5
    max_workers: 2
    debug: true
    
  # Production data collection
  production:
    trace_pattern: "/proj/siaiadm/AI_training_data/D2D/UCIe_Trace/pattern2/traces"
    vertical_dir: "/proj/siaiadm/AI_training_data/D2D/UCIe_Trace/vertical"
    output_dir: "./data/production_samples"
    param_type: "UCIE_PARAMS"
    max_samples: 100
    max_workers: 16
    debug: false
    
  # DDR-specific collection
  ddr:
    trace_pattern: "./test_data/ddr_traces"
    vertical_dir: "./test_data/ddr_vertical"
    output_dir: "./data/ddr_samples"
    param_type: "DDR_PARAMS"
    max_samples: 75
    max_workers: 12
    debug: false 